version: 2.1

jobs:
  build-app:
    docker:
      - image: cimg/node:current-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test

workflows:
  build:
    jobs:
      - build-app
